# Generated by Django 4.1 on 2022-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('url', models.URLField(max_length=500)),
                ('site', models.CharField(choices=[('mercado_livre', 'Mercado Livre'), ('amazon', 'Amazon'), ('magazine_luiza', 'Magazine Luiza'), ('americanas', 'Americanas')], default='Mercado Livre', max_length=14)),
            ],
        ),
    ]
