# Generated by Django 4.1 on 2022-08-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='desired_price',
            field=models.FloatField(default=10.0),
        ),
    ]
