# Generated by Django 4.1 on 2022-08-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='site',
            field=models.CharField(choices=[('Mercado Livre', 'Mercado Livre'), ('Amazon', 'Amazon'), ('Magazine Luiza', 'Magazine Luiza'), ('Americanas', 'Americanas')], max_length=14),
        ),
    ]
