# Generated by Django 4.1 on 2022-08-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_desired_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='prices',
            field=models.JSONField(null=True),
        ),
    ]
