# Generated by Django 4.1 on 2022-08-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_track_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
