# Generated by Django 4.1 on 2022-09-05 15:13

from django.db import migrations, models
import track.models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_track_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='prices',
            field=models.JSONField(default=track.models.get_default_json, null=True),
        ),
    ]
