# Generated by Django 4.1 on 2022-08-29 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_track_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
