# Generated by Django 4.1 on 2022-08-30 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import track.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0005_alter_track_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=track.models.NameField(max_length=100),
        ),
    ]
